language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_install:
  - sudo apt-get install -y libncursesw5-dev xorg-dev libxcb-dev
